### ISSUE TITLE
favicons deleted and default icons displayed if history is cleared.

### ISSUE THREAD

**Issue by jkvank** [umfana/FaviconBar#38]
When clearing the history in Safari, reopening the browser, only the default icons are displayed.
Is this expected behaviour ? Are users meant to reload the faviconbar.backup file after clearing history ?

**Comment by popcornhax** [comment]
Sorry for the delay in responding, my daughter just started her orchestra classes again and these couple hours each week is usually where I do Faviconbar development :)

I really don't want to erase my history, so I'm going to trust you on this one.  Faviconbar stores custom icons in Safari's Local Storage, and I am guessing based on your description that it must completely clear that out when history is cleared.

The only workaround I would have is uploading the custom icons to a web server and pointing at those when choosing the icon rather than dragging it into the browser, or reloading a backup file each time you clear history.  Sorry about that :(
