### ISSUE TITLE
Trying to fix FaviconBar

### ISSUE THREAD

**Issue by ghost** [umfana/FaviconBar#42]
Hi,
Yesterday I accidentally held my mouse and dragged on one of the favicons, causing it to move. When I let go, its name was appended to a different one's, instead of being in front of the icon.

I tried to move it back, but suddenly every icon disappeared and I was not allowed to add favicons. I reinstalled FaviconBar, but I still cannot add favicons from the settings page or by right-clicking.

**Comment by popcornhax** [comment]
Hi there.  That's a new one to me.  It sounds like something got corrupted.  If you clear Safari's cache it may erase whatever weirdness is going on.  Otherwise if you download the file from the Settings page and then Load it again that might work.  I'm just guessing at this point though.

If none of that works, and you can save your settings to a file, if you're willing to please paste/attach that here and I'll take a look.

**Comment by popcornhax** [comment]
Closing this out, if you want me to look at it again please let me know!
