### ISSUE TITLE
Safari Technology Preview - Not saving prefs

### ISSUE THREAD

**Issue by webxsite** [umfana/FaviconBar#45]
Firstly love this extension so much - I had to write in 👍 

Just recently Im having issue with your extension, but only in Safari Technology Preview.
Basically it wont save any changes, so as soon as I exit and come back in to the browser everything is back to default. 

This is not happening on the stock Safari it still works perfectly though. I thought I would make you aware incase some upcoming change could prevent the extension from working. Most probably a bug within STP but maybe there is also something wrong with my prefs - I already tried deleting cache and them, reinstalled STP but same issue.

**Comment by popcornhax** [comment]
Thanks for the heads up.  I tried the tech preview and the same thing is occurring for me.  The icons are all stored in whats called localStorage so its possible Apple changed something to disallow extensions from saving data there.  I will have to look into it.

This technology preview also finally changed what happens when you try to go to the extension gallery, it opens the App Store.  Apple has been pushing extensions to move into the App Store for awhile, so I will have to look into that in more detail.

**Comment by popcornhax** [comment]
This comment is for my own tracking purposes.  I'm hoping that this WebKit bug is what is causing the issue with FaviconBar in STP.  It was corrected on 4/9 but I don't have a way to test until the next STP release. It sounds very similar to what is going on here.

https://bugs.webkit.org/show_bug.cgi?id=184382

**Comment by popcornhax** [comment]
Safari Technology Preview R54 released today fixed this issue for me, so I'm guessing the bug above is what caused it.  I'm closing this issue but if you see any other weirdness please do let us know.  Thanks again for the report!
